apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-config
data:
  initdb.sql: |
    CREATE USER 'root'@'*' IDENTIFIED BY 'root';
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'*' WITH GRANT OPTION;
    FLUSH PRIVILEGES;
    CREATE DATABASE IF NOT EXISTS sehirler;

