---
- name: kubernetes
  shell: "kubectl version"
  args:
    executable: "/bin/bash"
  register: v1
- name: output
  debug:
    msg: "{{ v1.stdout_lines }}"
---
- name: docker
  shell: "docker version"
  args:
    executable: "/bin/bash"
  register: v2
- name: output
  debug:
    msg: "{{ v2.stdout_lines }}"