version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5001:5001"

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
