---
rsyslog_config: false


rsyslog_pri_domain_name: example.org

rsyslog_highprecision: false

rsyslog_allow_tcp: false

rsyslog_tcp_port: 514

rsyslog_allow_udp: false
rsyslog_udp_port: 514


rsyslog_servers:
  []
  
rsyslog_localfiles:
  - name: /var/log/auth.log
    proto: file
    selectors: auth,authpriv.*
  - name: /var/log/syslog
    proto: nosync
    selectors:
      - "*.*"
      - auth,authpriv.none
  
  - name: /var/log/kern.log
    proto: nosync
    selectors: kern.*
 
  - name: /var/log/mail.log
    selectors: mail.*
  
  - name: /var/log/mail.err
    selectors: mail.err

  - name: /var/log/news/news.crit
    selectors: news.crit
  - name: /var/log/news/news.err
    selectors: news.err
  - name: /var/log/news/news.notice
    proto: nosync
    selectors: news.notice

rsyslog_devices:
  - name: ":omusrmsg:*"
    selectors: "*.emerg"
 
  - name: /dev/xconsole
    proto: pipe
    selectors:
      - daemon.*
      - mail.*
      - news.err
      - "*.=debug"
      - "*.=info"
      - "*.=notice"
      - "*.=warn"

rsyslog_defaults: "{{ rsyslog_servers|union(rsyslog_localfiles)|union(rsyslog_devices) }}"
